
--- # Application configuration - config.yaml
author: admin
database:
        driver: dbni
        port: 3306
        dbname: mydb
        username: root
        password: pass

file_storage:
            namespace1: [name1,www.123.de]
            namespace2: [name2,www.456.de]
        